version: 2

models:
  - name: sales_info
    description: "Denormalized sales data with client, exchange currency and products"
  - name: sales_info_usd
    description: "same as sales_info but adding USD converted values"
    columns:
    - name: products_value_usd
      description: "products value converted to USD"
      tests:
        - not_null