version: 2

models:
  - name: compras_denormalizado
    description: "Dados de venda denormalizadas com clientes e cambio"
    tests:
      - sum_valor_match
    columns:
      - name: id
        description: "id unico para cada compra"
        tests:
          - unique
          - not_null
      
  - name: clientes
    description: "Dados tratados de clientes"
    columns:
      - name: id
        description: "id unico para cada cliente"
        tests:
          - unique
          - not_null
    
  - name: cambio
    description: "Dados tratados de cambio"
    columns:
      - name: mes
        description: "numero de mes para cambio, não pode ser nulo"
        tests:
          - not_null