version: 2

sources:
  - name: raw_layer
    tables:
      - name: orders
      - name: order_items
      - name: products
      - name: users
      - name: seller_conditions
      - name: currency_exchange_rates
      - name: payment_option
      - name: status